# Workflow for building and deploying pkgdown site
name: pkgdown

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pkgdown@v2
        with:
          website: dev

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = TRUE)
        shell: Rscript {0}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        if: ${{ github.event_name == 'push' }}
        with:
          branch: gh-pages
          folder: docs
